accounts/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
# from django.contrib.auth.views import LoginView
from accounts.views import (
    SubmittableLoginView, SubmittablePasswordChangeView, signup,
)

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', SubmittableLoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', SubmittablePasswordChangeView.as_view(), name='password_change')
]

api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import MovieViewSet

app_name = "api"

router = routers.DefaultRouter()
router.register('movies', MovieViewSet)

urlpatterns = [
    path('', include(router.urls))
]

hollymovies/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from viewer.views import (hello,
                          IndexView,
                          )

# hello jest funkcją i wywołujemy to normalnie, a moviesView i MoviesCreateView są klasami dlatego wywyołujemy jako widok

urlpatterns = [
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('hello/', hello, name='hello'),
    path('viewer/', include('viewer.urls', namespace='viewer')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# CRUD
# C create
# R read (List, Retrive)
# U update
# D deletefrom

viewer/urls.py
from django.contrib import admin
from django.urls import path
from viewer.views import (MoviesView,
                          MovieCreateView,
                          MovieUpdateView,
                          MovieDeleteView,
                          MovieDetailsView,
                          )

app_name = 'viewer'

# hello jest funkcją i wywołujemy to normalnie, a moviesView i MoviesCreateView są klasami dlatego wywyołujemy jako widok

urlpatterns = [
    path('movie/', MoviesView.as_view(), name="movie"),
    path('movie/<int:pk>/', MovieDetailsView.as_view(), name="movie_details"),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<int:pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<int:pk>/', MovieDeleteView.as_view(), name='movie_delete'),
]

# CRUD
# C create
# R read (List, Retrive)
# U update
# D delete

viewer/models.py
import os
from django.core.validators import FileExtensionValidator
from django.db.models import (
    CharField, Model, DateField, DateTimeField, ForeignKey, TextField, IntegerField, DO_NOTHING, ImageField
)


def get_upload_path(instance, filename):
    return os.path.join(f"movies/movie_{instance.id}", filename)


class Genre(Model):
    name = CharField(max_length=128)

    def __str__(self):
        return self.name


class Movie(Model):
    title = CharField(max_length=170)
    genre = ForeignKey(Genre, on_delete=DO_NOTHING)
    rating = IntegerField()
    released = DateField()
    description = TextField()
    image = ImageField(null=True, blank=True,
                       upload_to=get_upload_path,
                       validators=[
                           FileExtensionValidator(
                               allowed_extensions=['bmp', 'jpg', 'jpeg', 'jpe', 'gif', 'tif', 'tiff', 'png']
                           )]
                       )
    created = DateTimeField(auto_now_add=True)
    # nieobowiazkowa = TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.title} ({self.released.year}) - {self.genre.name}"

    def __repr__(self):
        return f"{self.title} ({self.released.year}) - {self.genre.name}"

    # def save(self):
    #     self.nieobowiazkowa = "123"
    #     super(Movie, self).save()

    # def save(self):
    #     self.title = self.title.capitalize()
    #     super(Movie, self).save()
    #

viewer/forms.py
import re
from datetime import date
from django.core.exceptions import ValidationError
from django.forms import (Form,
                          CharField,
                          ModelChoiceField,
                          IntegerField, DateField, Textarea, ModelForm)
from viewer.models import Genre, Movie


# class MojaKlasaPola(IntegerField):
#     def clean(self):
#         pass

# wtedy przy polu rating zamiast IntegerField trzeba dać MojaKlasaPola


def capitalized_validator(value):
    if value[0].islower():
        raise ValidationError('Value must be capitalized!')


# jeśli chcemy zdefiniować walidator to wszystkich pól tego samego typu to tworzymy klasę pola i tam dajemy walidator
class PastDateField(DateField):

    def validate(self, value):
        super().validate(value)
        if value > date.today():
            raise ValidationError("Future dates not allowed!!!")

    def clean(self, value):
        result = super().clean(value)
        return date(year=result.year, month=result.month, day=1)


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = "__all__" # ==> exclude = []

    title = CharField(validators=[capitalized_validator])
    rating = IntegerField(min_value=1, max_value=9)
    released = PastDateField()

    # title = CharField(max_length=170, validators=[capitalized_validator])
    # genre = ModelChoiceField(queryset=Genre.objects)
    # rating = IntegerField(min_value=1, max_value=9)
    # released = PastDateField()
    # description = CharField(widget=Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def clean_description(self):
        initial = self.cleaned_data['description']
        sentences = re.sub(r'\s*\.\s*', '.', initial).split('.')
        return '. '.join(sentence.capitalize() for sentence in sentences)
        # cleaned_data['description'] = clean_description()

    def clean(self):
        result = super().clean()
        if result['genre'].name == "Komedia" and result['rating'] > 5:
            # self.add_error('genre', 'to błąd - genre')
            # self.add_error('rating', 'to błąd - rating')
            raise ValidationError("Commedies are not so good to be rated over 5!")
        return result

viewer/views.py
from logging import getLogger

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView

from viewer.models import Movie, Genre
from django.views import View
from django.views.generic import (TemplateView,
                                  ListView,
                                  CreateView,
                                  DetailView,
                                  FormView,
                                  UpdateView,
                                  DeleteView
                                  )
from viewer.forms import MovieForm

'''
Pierwszy sposób przekazywania parametru s, wtedy trzeba w urlsach w ścieżce dać 'hello/<s>'
def hello(request, s):
    return HttpResponse(f'Hello, {s} world!')
    
def hello(request):
    s = request.GET.get('s', '')
    # w = request.GET.get('w', 'nie ma W')
    tekst = f"<b> Hello, {s} world! </b><br>" \
    #        f"{request.headers}"
            f"{request.META['REMOTE_ADDR']}"
    return HttpResponse(tekst)
    
    
    
    
def hello(request):
    try:
        s = int(request.GET.get('s', '')) + 10
    except Exception as ex:
        return HttpResponse(f"Coś poszło nie tak! Błąd: {ex}")

    tekst = f"Wartość o 10 większa: {s}"
    return HttpResponse(tekst)
    
'''

LOGGER = getLogger()


class StaffRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class SuperuserRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff and self.request.user.is_superuser


class NameRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.first_name != '' and user.last_name != ''


class IndexView(TemplateView):
    template_name = 'index.html'


class MovieDetailsView(DetailView):
    template_name = 'detail.html'
    model = Movie
    extra_context = {'lista': ['Dramat', 'Komedia', 'Sci-Fi', 'Historyczny', 'Thriller', 'Horror']}


class MovieDeleteView(StaffRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'movie_confirm_delete.html'
    model = Movie
    success_url = reverse_lazy('viewer:movie')
    permission_required = 'viewer.delete_movie'

    def test_func(self):
        return super().test_func() and self.request.user.is_superuser


class MovieUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'form.html'
    model = Movie
    form_class = MovieForm
    success_url = reverse_lazy('viewer:movie')
    permission_required = 'viewer.change_movie'

    def form_invalid(self, form):
        LOGGER.warning('User provided invalid data while updating a movie.')
        return super().form_invalid(form)


class MoviesView(ListView):
    template_name = 'movies.html'
    model = Movie
    paginate_by = 200   # w adresie strony ?page=2 przerzuca na drugą stronę

# extra_context = {'object_list': list(Movie.objects.all())}    -> to się dzieje w tle


# FormView -> CreateView i wtedy można usunąć def form_valid
class MovieCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = MovieForm
    success_url = reverse_lazy('viewer:movie_create')
    permission_required = 'viewer.add_movie'

    # def form_valid(self, form):
    #     result = super().form_valid(form)
    #     cleaned_data = form.cleaned_data
    #     Movie.objects.create(
    #         title=cleaned_data['title'],
    #         genre=cleaned_data['genre'],
    #         rating=cleaned_data['rating'],
    #         released=cleaned_data['released'],
    #         description=cleaned_data['description']
    #     )
    #     return result

    def form_invalid(self, form):
        LOGGER.warning('User provided an invalid data!')
        return super().form_invalid(form)

#
# class MoviesView(TemplateView):
#     template_name = 'movies.html'
#     extra_context = {'movies': Movie.objects.all().order_by('-released'),
#                      'title': "Wynik TemplateView"}



# class MoviesView(View):
#
#     def get(self, request):
#         return render(
#             request, template_name="movies.html",
#             context={'movies': Movie.objects.all().order_by('-released')}
#         )


# w context można też dać np. filter(genre__name=gatunek)


def movies(request):
    gatunek = request.GET.get('gatunek', '')
    return render(
        request, template_name="movies.html",
        context={'movies': Movie.objects.all().order_by('-released')}
    )


@login_required
def hello(request):
    s1 = request.GET.get('s1', '')
    user = request.user
    return render(
        request, template_name='hello.html',
        context={'adjectives': [s1, 'beautiful', 'wonderful', 'great'],
                 'title': s1,
                 'user': user}
        )



    # try:
    #     s = int(request.GET.get('s', ''))
    # except Exception as ex:
    #     return HttpResponse(f"Coś poszło nie tak! Błąd: {ex}")
    #
    # tekst = f"<b>Wartość s={s}</b><br>" \
    #         f"<a href='/hello/?s={s+1}'>link zwiększający o 1</a><br>" \
    #         f"<a href='/hello/?s={s-1}'>link zmniejszający o 1</a>"
    # return HttpResponse(tekst)

viewer/templates/base.html
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}"{% endif %}>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet"  href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</head>

<body>
{% include "navbar.html" %}

  <div class="container">
    <div class="jumbotron">
      {% block content %}{% endblock %}
    </div>
  </div>
</body>

</html>

viewer/templates/detail.html
{% extends "base.html" %}

{% block title %}
    Film {{ object.title }}
{% endblock %}


{% block content %}
<!--domyślnie jest autoescape on-->
{% autoescape off %}
    <h1> {{ object.title | escape }} </h1>
{{ object.genre.name }} ({{ object.released }})<br>
<hr>
{{ object.description | linebreaksbr }}
<!--linebreaksbr doda <br>, a linebreaks też to zrobi ale dodatkowo wsadzi całość w <p></p>-->
<hr>
Rating: {{ object.rating }}/9 <br>
<br>
<!--{{ lista }}<br>-->
<!--{{ lista.0 }}<br>-->
{% comment %}
{{ lista|join:" | " }}<br>
{{ lista | last }}<br>
{{ lista | length }}<br>
{{ lista | slice:":5" }}<br>
{% endcomment %}
<br>
{% if object.image %}
<img src="{{ object.image.url }}" height="150"><br><br>
{% endif %}
{% endautoescape %}

<a href="{% url 'viewer:movie_update' object.id %}" class="btn btn-success">Update</a>
<a href="{% url 'viewer:movie_delete' object.id %}" class="btn btn-danger">Delete</a>
{% endblock %}

viewer/templates/form.html
{% extends "base.html" %}

{% block title %}
    Formularz do tworzenia filmów
{% endblock %}

{% block content %}
<!--    <form method="post">-->
<!--        {% csrf_token %}-->
<!--        <table>{{ form }}</table>-->
<!--        <input type="submit" value="submit" class="btn btn-primary">-->
<!--    </form>-->

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.title.errors }}
            <label for="{{ form.title.id_for_label}}">Title*:</label>
            {{ form.title }}
        </div>
        <div class="row">
            <div class="col">
                <div class="form-group">
                    {{ form.genre.errors }}
                    <label for="{{ form.genre.id_for_label }}">Genre*:</label>
                    {{ form.genre }}
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    {{ form.rating.errors }}
                    <label for="{{ form.rating.id_for_label }}">Rating*:</label>
                    {{ form.rating }}
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    {{ form.released.errors }}
                    <label for="{{ form.released.id_for_label }}">Released*:</label>
                    {{ form.released }}
                </div>
            </div>
        </div>
        <div class="form-group">
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}">Description:</label>
                    {{ form.description }}
        </div>
        <div class="form-group">
            {{ form.image.errors }}
            <label for="{{ form.image.id_for_label }}">Image:</label>
                    {{ form.image }}
        </div>
        <input type="submit" value="submit" class="btn btn-primary">
    </form>
{% endblock %}

viewer/templates/hello.html
{% extends "base.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}

    <h1>Welcome to HollyMovies!</h1>
    {% for adjective in adjectives %}
        {% if adjective != 'cruel' %}
            <p>This is a {{ adjective }} world...</p>
        {% endif %}
    {% endfor %}
Użytkownik: {{ user }}
{{ title }}
{% endblock %}

viewer/templates/index.html
{% extends "base.html" %}

{% block title %}
Holly Movies
{% endblock %}


{% block content %}
<h1>Welcome on our Holly Movies web page!</h1>
<br>
<br>
<a href="{% url 'viewer:movie' %}" class="btn btn-primary">Our movie list</a>
{% endblock %}

viewer/templates/movie_confirm_delete.html
{% extends "base.html" %}

{% block title %}
    Usuwanie filmu {{ object.title }}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            Are you sure you want to delete movie "{{object.title}}" from database?
        </p>
        <input type="submit" value="Submit" class="btn btn-danger">
    </form>
{% endblock %}

viewer/templates/movies.html
{% extends "base.html" %}

{% block title %}
    Lista filmów
{% endblock %}

{% block content %}
    <h1>Welcome to HollyMovies!</h1>
    We have {{ object_list | length }} movie{{ object_list|length|pluralize:"s" }}
    <ul>
<!--    object_list jest z klasy MoviesView    -->
        {% for movie in object_list %}
        <li>
            <a href="{% url 'viewer:movie_details' movie.id %}">{{ movie.title | upper }} ({{ movie.released.year }}) - {{ movie.genre.name }}, {{ movie.description | truncatewords:4 }}</a>
        </li>
        {% empty %}
        <h5>Nie ma nic do wyświetlenia!</h5>
        {% endfor %}
    </ul>
<a href="{% url 'viewer:movie_create' %}" class="btn btn-info">Add movie</a>

{% endblock %}

viewer/templates/navbar.html
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container fixed">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'viewer:movie' %}">HollyMovies</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'hello' %}">Hello</a>
        </div>
      </div>
    </div>
   {% if user.is_authenticated %}
      <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
      {% if user.first_name %}Hello, {{ user.first_name }}!
        {% else %}Hello, {{ user.username }}!
        {% endif %}
      </a>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item text-right" href="{% url 'accounts:logout' %}">Logout</a>
      <a class="dropdown-item text-right" href="{% url 'accounts:password_change' %}">Change password</a>
    </div>
  {% else %}
    <a class="nav-link active dropdown-toggle" href="#" data-toggle="dropdown">
      You are not logged in.
    </a>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item text-right" href="{% url 'accounts:login' %}">Login</a>
      <a class="dropdown-item text-right" href="{% url 'accounts:signup' %}">Register</a>
    </div>
  {% endif %}
  </nav>